export const Countries = [
  { code: "AF", name: "AFGHANISTAN" },
  { code: "AL", name: "ALBANIA" },
  { code: "DZ", name: "ALGERIA" },
  { code: "AS", name: "AMERICAN SAMOA" },
  { code: "AD", name: "ANDORRA" },
  { code: "AO", name: "ANGOLA" },
  { code: "AI", name: "ANGUILLA" },
  { code: "AQ", name: "ANTARCTICA" },
  { code: "AG", name: "ANTIGUA AND BARBUDA" },
  { code: "AR", name: "ARGENTINA" },
  { code: "AM", name: "ARMENIA" },
  { code: "AW", name: "ARUBA" },
  { code: "AU", name: "AUSTRALIA" },
  { code: "AT", name: "AUSTRIA" },
  { code: "AZ", name: "AZERBAIJAN" },
  { code: "BS", name: "BAHAMAS" },
  { code: "BH", name: "BAHRAIN" },
  { code: "BD", name: "BANGLADESH" },
  { code: "BB", name: "BARBADOS" },
  { code: "BY", name: "BELARUS" },
  { code: "BE", name: "BELGIUM" },
  { code: "BZ", name: "BELIZE" },
  { code: "BJ", name: "BENIN" },
  { code: "BM", name: "BERMUDA" },
  { code: "BT", name: "BHUTAN" },
  { code: "BO", name: "BOLIVIA" },
  { code: "BA", name: "BOSNIA AND HERZEGOVINA" },
  { code: "BW", name: "BOTSWANA" },
  { code: "BR", name: "BRAZIL" },
  { code: "BN", name: "BRUNEI DARUSSALAM" },
  { code: "BG", name: "BULGARIA" },
  { code: "BF", name: "BURKINA FASO" },
  { code: "BI", name: "BURUNDI" },
  { code: "KH", name: "CAMBODIA" },
  { code: "CM", name: "CAMEROON" },
  { code: "CA", name: "CANADA" },
  { code: "CV", name: "CAPE VERDE" },
  { code: "KY", name: "CAYMAN ISLANDS" },
  { code: "CF", name: "CENTRAL AFRICAN REPUBLIC" },
  { code: "TD", name: "CHAD" },
  { code: "CL", name: "CHILE" },
  { code: "CN", name: "CHINA" },
  { code: "CO", name: "COLOMBIA" },
  { code: "CR", name: "COSTA RICA" },
  { code: "HR", name: "CROATIA" },
  { code: "CU", name: "CUBA" },
  { code: "CY", name: "CYPRUS" },
  { code: "CZ", name: "CZECH REPUBLIC" },
  { code: "DK", name: "DENMARK" },
  { code: "DO", name: "DOMINICAN REPUBLIC" },
  { code: "EC", name: "ECUADOR" },
  { code: "EG", name: "EGYPT" },
  { code: "SV", name: "EL SALVADOR" },
  { code: "EE", name: "ESTONIA" },
  { code: "ET", name: "ETHIOPIA" },
  { code: "FI", name: "FINLAND" },
  { code: "FR", name: "FRANCE" },
  { code: "DE", name: "GERMANY" },
  { code: "GH", name: "GHANA" },
  { code: "GR", name: "GREECE" },
  { code: "GT", name: "GUATEMALA" },
  { code: "GY", name: "GUYANA" },
  { code: "HT", name: "HAITI" },
  { code: "HN", name: "HONDURAS" },
  { code: "HK", name: "HONG KONG" },
  { code: "HU", name: "HUNGARY" },
  { code: "IS", name: "ICELAND" },
  { code: "IN", name: "INDIA" },
  { code: "ID", name: "INDONESIA" },
  { code: "IR", name: "IRAN" },
  { code: "IE", name: "IRELAND" },
  { code: "IL", name: "ISRAEL" },
  { code: "IT", name: "ITALY" },
  { code: "JM", name: "JAMAICA" },
  { code: "JP", name: "JAPAN" },
  { code: "JO", name: "JORDAN" },
  { code: "KZ", name: "KAZAKHSTAN" },
  { code: "KE", name: "KENYA" },
  { code: "KR", name: "KOREA" },
  { code: "KW", name: "KUWAIT" },
  { code: "LV", name: "LATVIA" },
  { code: "LB", name: "LEBANON" },
  { code: "LY", name: "LIBYA" },
  { code: "LT", name: "LITHUANIA" },
  { code: "LU", name: "LUXEMBOURG" },
  { code: "MY", name: "MALAYSIA" },
  { code: "MX", name: "MEXICO" },
  { code: "MA", name: "MOROCCO" },
  { code: "NL", name: "NETHERLANDS" },
  { code: "NZ", name: "NEW ZEALAND" },
  { code: "NI", name: "NICARAGUA" },
  { code: "NG", name: "NIGERIA" },
  { code: "NO", name: "NORWAY" },
  { code: "OM", name: "OMAN" },
  { code: "PA", name: "PANAMA" },
  { code: "PY", name: "PARAGUAY" },
  { code: "PE", name: "PERU" },
  { code: "PH", name: "PHILIPPINES" },
  { code: "PL", name: "POLAND" },
  { code: "PT", name: "PORTUGAL" },
  { code: "PR", name: "PUERTO RICO" },
  { code: "QA", name: "QATAR" },
  { code: "RO", name: "ROMANIA" },
  { code: "RU", name: "RUSSIA" },
  { code: "SA", name: "SAUDI ARABIA" },
  { code: "SN", name: "SENEGAL" },
  { code: "RS", name: "SERBIA" },
  { code: "SG", name: "SINGAPORE" },
  { code: "ZA", name: "SOUTH AFRICA" },
  { code: "ES", name: "SPAIN" },
  { code: "SE", name: "SWEDEN" },
  { code: "CH", name: "SWITZERLAND" },
  { code: "TH", name: "THAILAND" },
  { code: "TR", name: "TURKEY" },
  { code: "UA", name: "UKRAINE" },
  { code: "AE", name: "UNITED ARAB EMIRATES" },
  { code: "GB", name: "UNITED KINGDOM" },
  { code: "US", name: "UNITED STATES" },
  { code: "UY", name: "URUGUAY" },
  { code: "VE", name: "VENEZUELA" },
  { code: "VN", name: "VIETNAM" },
];
